services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 5